// <auto-generated />
using BankWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251019055403_SeedRefresh")]
    partial class SeedRefresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.HasIndex("Username");

                    b.ToTable("Bank_Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            Balance = 9256m,
                            Email = "linda_reyes@email.com",
                            Name = "Linda's Account 1",
                            Username = "lindareyes520"
                        },
                        new
                        {
                            AccountNumber = 2,
                            Balance = 536m,
                            Email = "linda_reyes@email.com",
                            Name = "Linda's Account 2",
                            Username = "lindareyes520"
                        },
                        new
                        {
                            AccountNumber = 3,
                            Balance = 488m,
                            Email = "linda_reyes@email.com",
                            Name = "Linda's Account 3",
                            Username = "lindareyes520"
                        },
                        new
                        {
                            AccountNumber = 4,
                            Balance = 5411m,
                            Email = "linda_reyes@email.com",
                            Name = "Linda's Account 4",
                            Username = "lindareyes520"
                        },
                        new
                        {
                            AccountNumber = 5,
                            Balance = 8985m,
                            Email = "james_green@email.com",
                            Name = "James's Account 1",
                            Username = "jamesgreen536"
                        },
                        new
                        {
                            AccountNumber = 6,
                            Balance = 9309m,
                            Email = "james_green@email.com",
                            Name = "James's Account 2",
                            Username = "jamesgreen536"
                        },
                        new
                        {
                            AccountNumber = 7,
                            Balance = 3626m,
                            Email = "james_green@email.com",
                            Name = "James's Account 3",
                            Username = "jamesgreen536"
                        },
                        new
                        {
                            AccountNumber = 8,
                            Balance = 6023m,
                            Email = "james_green@email.com",
                            Name = "James's Account 4",
                            Username = "jamesgreen536"
                        },
                        new
                        {
                            AccountNumber = 9,
                            Balance = 2351m,
                            Email = "james_green@email.com",
                            Name = "James's Account 5",
                            Username = "jamesgreen536"
                        },
                        new
                        {
                            AccountNumber = 10,
                            Balance = 5975m,
                            Email = "mary_green@email.com",
                            Name = "Mary's Account 1",
                            Username = "marygreen176"
                        },
                        new
                        {
                            AccountNumber = 11,
                            Balance = 3657m,
                            Email = "mary_green@email.com",
                            Name = "Mary's Account 2",
                            Username = "marygreen176"
                        },
                        new
                        {
                            AccountNumber = 12,
                            Balance = 6397m,
                            Email = "mary_green@email.com",
                            Name = "Mary's Account 3",
                            Username = "marygreen176"
                        },
                        new
                        {
                            AccountNumber = 13,
                            Balance = 2681m,
                            Email = "mary_green@email.com",
                            Name = "Mary's Account 4",
                            Username = "marygreen176"
                        },
                        new
                        {
                            AccountNumber = 14,
                            Balance = 4845m,
                            Email = "jessica_edwards@email.com",
                            Name = "Jessica's Account 1",
                            Username = "jessicaedwards410"
                        },
                        new
                        {
                            AccountNumber = 15,
                            Balance = 8818m,
                            Email = "jessica_edwards@email.com",
                            Name = "Jessica's Account 2",
                            Username = "jessicaedwards410"
                        },
                        new
                        {
                            AccountNumber = 16,
                            Balance = 8038m,
                            Email = "jessica_edwards@email.com",
                            Name = "Jessica's Account 3",
                            Username = "jessicaedwards410"
                        },
                        new
                        {
                            AccountNumber = 17,
                            Balance = 7951m,
                            Email = "jessica_edwards@email.com",
                            Name = "Jessica's Account 4",
                            Username = "jessicaedwards410"
                        },
                        new
                        {
                            AccountNumber = 18,
                            Balance = 5173m,
                            Email = "jessica_edwards@email.com",
                            Name = "Jessica's Account 5",
                            Username = "jessicaedwards410"
                        },
                        new
                        {
                            AccountNumber = 19,
                            Balance = 3138m,
                            Email = "karen_green@email.com",
                            Name = "Karen's Account 1",
                            Username = "karengreen872"
                        },
                        new
                        {
                            AccountNumber = 20,
                            Balance = 2496m,
                            Email = "karen_green@email.com",
                            Name = "Karen's Account 2",
                            Username = "karengreen872"
                        },
                        new
                        {
                            AccountNumber = 21,
                            Balance = 4309m,
                            Email = "karen_green@email.com",
                            Name = "Karen's Account 3",
                            Username = "karengreen872"
                        },
                        new
                        {
                            AccountNumber = 22,
                            Balance = 9724m,
                            Email = "karen_green@email.com",
                            Name = "Karen's Account 4",
                            Username = "karengreen872"
                        },
                        new
                        {
                            AccountNumber = 23,
                            Balance = 1590m,
                            Email = "karen_green@email.com",
                            Name = "Karen's Account 5",
                            Username = "karengreen872"
                        },
                        new
                        {
                            AccountNumber = 24,
                            Balance = 8945m,
                            Email = "linda_flores@email.com",
                            Name = "Linda's Account 1",
                            Username = "lindaflores538"
                        },
                        new
                        {
                            AccountNumber = 25,
                            Balance = 8543m,
                            Email = "linda_gomez@email.com",
                            Name = "Linda's Account 1",
                            Username = "lindagomez831"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN ('Deposit','Withdraw')");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = 1,
                            Amount = 426m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = 1,
                            Amount = 303m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountNumber = 1,
                            Amount = 570m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountNumber = 1,
                            Amount = 298m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountNumber = 1,
                            Amount = 506m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountNumber = 1,
                            Amount = 123m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountNumber = 1,
                            Amount = 342m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountNumber = 1,
                            Amount = 60m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountNumber = 1,
                            Amount = 818m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountNumber = 2,
                            Amount = 462m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountNumber = 2,
                            Amount = 669m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountNumber = 3,
                            Amount = 969m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountNumber = 3,
                            Amount = 36m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountNumber = 3,
                            Amount = 175m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountNumber = 3,
                            Amount = 154m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountNumber = 4,
                            Amount = 113m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountNumber = 4,
                            Amount = 459m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountNumber = 5,
                            Amount = 173m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountNumber = 5,
                            Amount = 522m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountNumber = 5,
                            Amount = 720m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountNumber = 5,
                            Amount = 363m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountNumber = 5,
                            Amount = 957m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountNumber = 5,
                            Amount = 721m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountNumber = 6,
                            Amount = 659m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountNumber = 6,
                            Amount = 950m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountNumber = 6,
                            Amount = 166m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 27,
                            AccountNumber = 6,
                            Amount = 543m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 28,
                            AccountNumber = 6,
                            Amount = 760m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 29,
                            AccountNumber = 6,
                            Amount = 663m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 30,
                            AccountNumber = 6,
                            Amount = 507m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 31,
                            AccountNumber = 7,
                            Amount = 24m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 32,
                            AccountNumber = 7,
                            Amount = 439m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 33,
                            AccountNumber = 7,
                            Amount = 301m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 34,
                            AccountNumber = 7,
                            Amount = 379m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 35,
                            AccountNumber = 7,
                            Amount = 138m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 36,
                            AccountNumber = 7,
                            Amount = 730m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 37,
                            AccountNumber = 7,
                            Amount = 775m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 38,
                            AccountNumber = 7,
                            Amount = 920m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 39,
                            AccountNumber = 7,
                            Amount = 126m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 40,
                            AccountNumber = 7,
                            Amount = 337m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 41,
                            AccountNumber = 7,
                            Amount = 794m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 42,
                            AccountNumber = 7,
                            Amount = 176m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 43,
                            AccountNumber = 8,
                            Amount = 285m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 44,
                            AccountNumber = 8,
                            Amount = 858m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 45,
                            AccountNumber = 8,
                            Amount = 725m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 46,
                            AccountNumber = 8,
                            Amount = 213m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 47,
                            AccountNumber = 8,
                            Amount = 618m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 48,
                            AccountNumber = 8,
                            Amount = 735m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 49,
                            AccountNumber = 8,
                            Amount = 111m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 50,
                            AccountNumber = 8,
                            Amount = 677m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 51,
                            AccountNumber = 9,
                            Amount = 604m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 52,
                            AccountNumber = 9,
                            Amount = 134m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 53,
                            AccountNumber = 9,
                            Amount = 434m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 54,
                            AccountNumber = 9,
                            Amount = 607m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 55,
                            AccountNumber = 10,
                            Amount = 320m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 56,
                            AccountNumber = 10,
                            Amount = 83m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 57,
                            AccountNumber = 10,
                            Amount = 754m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 58,
                            AccountNumber = 10,
                            Amount = 12m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 59,
                            AccountNumber = 10,
                            Amount = 154m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 60,
                            AccountNumber = 11,
                            Amount = 397m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 61,
                            AccountNumber = 11,
                            Amount = 294m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 62,
                            AccountNumber = 11,
                            Amount = 26m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 63,
                            AccountNumber = 11,
                            Amount = 316m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 64,
                            AccountNumber = 11,
                            Amount = 772m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 65,
                            AccountNumber = 11,
                            Amount = 868m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 66,
                            AccountNumber = 11,
                            Amount = 621m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 67,
                            AccountNumber = 11,
                            Amount = 301m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 68,
                            AccountNumber = 11,
                            Amount = 846m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 69,
                            AccountNumber = 11,
                            Amount = 978m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 70,
                            AccountNumber = 11,
                            Amount = 680m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 71,
                            AccountNumber = 11,
                            Amount = 12m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 72,
                            AccountNumber = 12,
                            Amount = 538m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 73,
                            AccountNumber = 12,
                            Amount = 97m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 74,
                            AccountNumber = 12,
                            Amount = 833m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 75,
                            AccountNumber = 12,
                            Amount = 75m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 76,
                            AccountNumber = 12,
                            Amount = 168m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 77,
                            AccountNumber = 12,
                            Amount = 862m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 78,
                            AccountNumber = 12,
                            Amount = 950m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 79,
                            AccountNumber = 12,
                            Amount = 22m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 80,
                            AccountNumber = 12,
                            Amount = 234m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 81,
                            AccountNumber = 12,
                            Amount = 54m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 82,
                            AccountNumber = 12,
                            Amount = 911m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 83,
                            AccountNumber = 12,
                            Amount = 199m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 84,
                            AccountNumber = 13,
                            Amount = 478m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 85,
                            AccountNumber = 13,
                            Amount = 965m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 86,
                            AccountNumber = 13,
                            Amount = 513m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 87,
                            AccountNumber = 14,
                            Amount = 598m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 88,
                            AccountNumber = 14,
                            Amount = 813m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 89,
                            AccountNumber = 14,
                            Amount = 334m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 90,
                            AccountNumber = 14,
                            Amount = 445m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 91,
                            AccountNumber = 14,
                            Amount = 943m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 92,
                            AccountNumber = 14,
                            Amount = 353m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 93,
                            AccountNumber = 14,
                            Amount = 606m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 94,
                            AccountNumber = 15,
                            Amount = 923m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 95,
                            AccountNumber = 15,
                            Amount = 465m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 96,
                            AccountNumber = 15,
                            Amount = 842m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 97,
                            AccountNumber = 15,
                            Amount = 482m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 98,
                            AccountNumber = 15,
                            Amount = 112m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 99,
                            AccountNumber = 15,
                            Amount = 679m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 100,
                            AccountNumber = 15,
                            Amount = 270m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 101,
                            AccountNumber = 15,
                            Amount = 568m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 102,
                            AccountNumber = 15,
                            Amount = 323m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 103,
                            AccountNumber = 15,
                            Amount = 369m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 104,
                            AccountNumber = 15,
                            Amount = 914m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 105,
                            AccountNumber = 15,
                            Amount = 485m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 106,
                            AccountNumber = 16,
                            Amount = 217m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 107,
                            AccountNumber = 17,
                            Amount = 305m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 108,
                            AccountNumber = 17,
                            Amount = 770m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 109,
                            AccountNumber = 17,
                            Amount = 152m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 110,
                            AccountNumber = 17,
                            Amount = 281m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 111,
                            AccountNumber = 18,
                            Amount = 84m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 112,
                            AccountNumber = 18,
                            Amount = 984m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 113,
                            AccountNumber = 18,
                            Amount = 722m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 114,
                            AccountNumber = 18,
                            Amount = 247m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 115,
                            AccountNumber = 18,
                            Amount = 277m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 116,
                            AccountNumber = 18,
                            Amount = 57m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 117,
                            AccountNumber = 18,
                            Amount = 184m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 118,
                            AccountNumber = 18,
                            Amount = 257m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 119,
                            AccountNumber = 19,
                            Amount = 597m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 120,
                            AccountNumber = 19,
                            Amount = 193m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 121,
                            AccountNumber = 19,
                            Amount = 209m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 122,
                            AccountNumber = 19,
                            Amount = 49m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 123,
                            AccountNumber = 19,
                            Amount = 724m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 124,
                            AccountNumber = 19,
                            Amount = 703m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 125,
                            AccountNumber = 19,
                            Amount = 430m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 126,
                            AccountNumber = 19,
                            Amount = 258m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 127,
                            AccountNumber = 20,
                            Amount = 294m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 128,
                            AccountNumber = 20,
                            Amount = 791m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 129,
                            AccountNumber = 20,
                            Amount = 597m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 130,
                            AccountNumber = 20,
                            Amount = 337m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 131,
                            AccountNumber = 20,
                            Amount = 886m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 132,
                            AccountNumber = 20,
                            Amount = 39m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 133,
                            AccountNumber = 20,
                            Amount = 224m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 134,
                            AccountNumber = 20,
                            Amount = 195m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 135,
                            AccountNumber = 20,
                            Amount = 453m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 136,
                            AccountNumber = 20,
                            Amount = 158m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 137,
                            AccountNumber = 20,
                            Amount = 211m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 138,
                            AccountNumber = 20,
                            Amount = 232m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 139,
                            AccountNumber = 21,
                            Amount = 877m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 140,
                            AccountNumber = 22,
                            Amount = 165m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 141,
                            AccountNumber = 22,
                            Amount = 266m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 142,
                            AccountNumber = 22,
                            Amount = 380m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 143,
                            AccountNumber = 22,
                            Amount = 37m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 144,
                            AccountNumber = 22,
                            Amount = 322m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 145,
                            AccountNumber = 22,
                            Amount = 757m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 146,
                            AccountNumber = 22,
                            Amount = 245m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 147,
                            AccountNumber = 22,
                            Amount = 860m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 148,
                            AccountNumber = 22,
                            Amount = 399m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 149,
                            AccountNumber = 22,
                            Amount = 505m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 150,
                            AccountNumber = 22,
                            Amount = 627m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 151,
                            AccountNumber = 22,
                            Amount = 134m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 152,
                            AccountNumber = 23,
                            Amount = 725m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 153,
                            AccountNumber = 23,
                            Amount = 466m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 154,
                            AccountNumber = 23,
                            Amount = 743m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 155,
                            AccountNumber = 23,
                            Amount = 562m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 156,
                            AccountNumber = 23,
                            Amount = 936m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 157,
                            AccountNumber = 23,
                            Amount = 812m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 158,
                            AccountNumber = 23,
                            Amount = 86m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 159,
                            AccountNumber = 23,
                            Amount = 920m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 160,
                            AccountNumber = 23,
                            Amount = 676m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 161,
                            AccountNumber = 24,
                            Amount = 602m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 162,
                            AccountNumber = 25,
                            Amount = 175m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 163,
                            AccountNumber = 25,
                            Amount = 567m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 164,
                            AccountNumber = 25,
                            Amount = 70m,
                            Type = "Withdraw"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Username = "lindareyes520",
                            Address = "86 Reyes Street, City 9",
                            Email = "linda_reyes@email.com",
                            Password = "pass8585",
                            Phone = "0430753479",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\4.jpg"
                        },
                        new
                        {
                            Username = "jamesgreen536",
                            Address = "136 Green Street, City 7",
                            Email = "james_green@email.com",
                            Password = "pass2583",
                            Phone = "0433541641",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\2.jpg"
                        },
                        new
                        {
                            Username = "marygreen176",
                            Address = "197 Green Street, City 1",
                            Email = "mary_green@email.com",
                            Password = "pass5490",
                            Phone = "0496277608",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "jessicaedwards410",
                            Address = "117 Edwards Street, City 4",
                            Email = "jessica_edwards@email.com",
                            Password = "pass5811",
                            Phone = "0445853982",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "karengreen872",
                            Address = "199 Green Street, City 4",
                            Email = "karen_green@email.com",
                            Password = "pass8499",
                            Phone = "0463737057",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\4.jpg"
                        },
                        new
                        {
                            Username = "lindaflores538",
                            Address = "145 Flores Street, City 9",
                            Email = "linda_flores@email.com",
                            Password = "pass7874",
                            Phone = "0449920721",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\2.jpg"
                        },
                        new
                        {
                            Username = "lindagomez831",
                            Address = "131 Gomez Street, City 3",
                            Email = "linda_gomez@email.com",
                            Password = "pass5206",
                            Phone = "0438736231",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "BankAdmin",
                            Address = "Head Office",
                            Email = "admin@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "BankAdmin2",
                            Address = "Head Office",
                            Email = "admin2@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "BankAdmin3",
                            Address = "Head Office",
                            Email = "admin3@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "MoeDegrasse",
                            Address = "17 Harper Street, City 2",
                            Email = "MoeDegrasse@email.com",
                            Password = "pass12",
                            Phone = "0444122322",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.HasOne("BankWebService.Models.UserProfile", "UserProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankWebService.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
