// <auto-generated />
using BankWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251018151738_SeedRefresh")]
    partial class SeedRefresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.HasIndex("Username");

                    b.ToTable("Bank_Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            Balance = 6011m,
                            Email = "karen_collins@email.com",
                            Username = "karencollins863"
                        },
                        new
                        {
                            AccountNumber = 2,
                            Balance = 4893m,
                            Email = "thomas_roberts@email.com",
                            Username = "thomasroberts138"
                        },
                        new
                        {
                            AccountNumber = 3,
                            Balance = 7585m,
                            Email = "thomas_roberts@email.com",
                            Username = "thomasroberts138"
                        },
                        new
                        {
                            AccountNumber = 4,
                            Balance = 8037m,
                            Email = "thomas_roberts@email.com",
                            Username = "thomasroberts138"
                        },
                        new
                        {
                            AccountNumber = 5,
                            Balance = 8000m,
                            Email = "sarah_diaz@email.com",
                            Username = "sarahdiaz875"
                        },
                        new
                        {
                            AccountNumber = 6,
                            Balance = 8818m,
                            Email = "sarah_diaz@email.com",
                            Username = "sarahdiaz875"
                        },
                        new
                        {
                            AccountNumber = 7,
                            Balance = 1191m,
                            Email = "sarah_diaz@email.com",
                            Username = "sarahdiaz875"
                        },
                        new
                        {
                            AccountNumber = 8,
                            Balance = 8024m,
                            Email = "susan_carter@email.com",
                            Username = "susancarter997"
                        },
                        new
                        {
                            AccountNumber = 9,
                            Balance = 3976m,
                            Email = "susan_carter@email.com",
                            Username = "susancarter997"
                        },
                        new
                        {
                            AccountNumber = 10,
                            Balance = 2501m,
                            Email = "susan_carter@email.com",
                            Username = "susancarter997"
                        },
                        new
                        {
                            AccountNumber = 11,
                            Balance = 4135m,
                            Email = "karen_nelson@email.com",
                            Username = "karennelson920"
                        },
                        new
                        {
                            AccountNumber = 12,
                            Balance = 2711m,
                            Email = "karen_nelson@email.com",
                            Username = "karennelson920"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN ('Deposit','Withdraw')");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = 1,
                            Amount = 558m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = 1,
                            Amount = 162m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountNumber = 1,
                            Amount = 53m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountNumber = 1,
                            Amount = 52m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountNumber = 1,
                            Amount = 902m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountNumber = 1,
                            Amount = 701m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountNumber = 1,
                            Amount = 895m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountNumber = 1,
                            Amount = 829m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountNumber = 1,
                            Amount = 98m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountNumber = 2,
                            Amount = 470m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountNumber = 2,
                            Amount = 657m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountNumber = 2,
                            Amount = 501m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountNumber = 3,
                            Amount = 715m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountNumber = 3,
                            Amount = 924m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountNumber = 3,
                            Amount = 713m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountNumber = 3,
                            Amount = 148m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountNumber = 3,
                            Amount = 374m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountNumber = 4,
                            Amount = 349m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountNumber = 4,
                            Amount = 350m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountNumber = 4,
                            Amount = 64m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountNumber = 4,
                            Amount = 927m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountNumber = 5,
                            Amount = 198m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountNumber = 5,
                            Amount = 559m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountNumber = 5,
                            Amount = 382m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountNumber = 6,
                            Amount = 790m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountNumber = 6,
                            Amount = 131m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 27,
                            AccountNumber = 6,
                            Amount = 414m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 28,
                            AccountNumber = 6,
                            Amount = 573m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 29,
                            AccountNumber = 6,
                            Amount = 775m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 30,
                            AccountNumber = 6,
                            Amount = 656m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 31,
                            AccountNumber = 6,
                            Amount = 811m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 32,
                            AccountNumber = 6,
                            Amount = 252m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 33,
                            AccountNumber = 6,
                            Amount = 104m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 34,
                            AccountNumber = 7,
                            Amount = 814m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 35,
                            AccountNumber = 7,
                            Amount = 752m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 36,
                            AccountNumber = 7,
                            Amount = 354m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 37,
                            AccountNumber = 7,
                            Amount = 542m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 38,
                            AccountNumber = 7,
                            Amount = 650m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 39,
                            AccountNumber = 8,
                            Amount = 378m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 40,
                            AccountNumber = 8,
                            Amount = 544m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 41,
                            AccountNumber = 8,
                            Amount = 126m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 42,
                            AccountNumber = 8,
                            Amount = 197m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 43,
                            AccountNumber = 9,
                            Amount = 194m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 44,
                            AccountNumber = 9,
                            Amount = 109m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 45,
                            AccountNumber = 10,
                            Amount = 512m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 46,
                            AccountNumber = 10,
                            Amount = 526m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 47,
                            AccountNumber = 10,
                            Amount = 928m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 48,
                            AccountNumber = 10,
                            Amount = 102m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 49,
                            AccountNumber = 10,
                            Amount = 386m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 50,
                            AccountNumber = 11,
                            Amount = 353m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 51,
                            AccountNumber = 12,
                            Amount = 273m,
                            Type = "Withdraw"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Username = "karencollins863",
                            Address = "130 Collins Street, City 2",
                            Email = "karen_collins@email.com",
                            Password = "pass9615",
                            Phone = "0496715500",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\2.jpg"
                        },
                        new
                        {
                            Username = "thomasroberts138",
                            Address = "106 Roberts Street, City 2",
                            Email = "thomas_roberts@email.com",
                            Password = "pass2992",
                            Phone = "0461647360",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        },
                        new
                        {
                            Username = "sarahdiaz875",
                            Address = "192 Diaz Street, City 7",
                            Email = "sarah_diaz@email.com",
                            Password = "pass3481",
                            Phone = "0475742900",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\4.jpg"
                        },
                        new
                        {
                            Username = "susancarter997",
                            Address = "88 Carter Street, City 5",
                            Email = "susan_carter@email.com",
                            Password = "pass2035",
                            Phone = "0441090544",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "karennelson920",
                            Address = "111 Nelson Street, City 2",
                            Email = "karen_nelson@email.com",
                            Password = "pass4169",
                            Phone = "0468909782",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "BankAdmin",
                            Address = "Head Office",
                            Email = "admin@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "BankAdmin2",
                            Address = "Head Office",
                            Email = "admin2@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "BankAdmin3",
                            Address = "Head Office",
                            Email = "admin3@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "MoeDegrasse",
                            Address = "17 Harper Street, City 2",
                            Email = "MoeDegrasse@email.com",
                            Password = "pass12",
                            Phone = "0444122322",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.HasOne("BankWebService.Models.UserProfile", "UserProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankWebService.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
