// <auto-generated />
using BankWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251016122142_SeedRefresh")]
    partial class SeedRefresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.HasIndex("Username");

                    b.ToTable("Bank_Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            Balance = 1918m,
                            Email = "james_collins@email.com",
                            Username = "jamescollins161"
                        },
                        new
                        {
                            AccountNumber = 2,
                            Balance = 1659m,
                            Email = "james_collins@email.com",
                            Username = "jamescollins161"
                        },
                        new
                        {
                            AccountNumber = 3,
                            Balance = 6578m,
                            Email = "james_collins@email.com",
                            Username = "jamescollins161"
                        },
                        new
                        {
                            AccountNumber = 4,
                            Balance = 3510m,
                            Email = "linda_reyes@email.com",
                            Username = "lindareyes715"
                        },
                        new
                        {
                            AccountNumber = 5,
                            Balance = 2879m,
                            Email = "linda_reyes@email.com",
                            Username = "lindareyes715"
                        },
                        new
                        {
                            AccountNumber = 6,
                            Balance = 387m,
                            Email = "linda_reyes@email.com",
                            Username = "lindareyes715"
                        },
                        new
                        {
                            AccountNumber = 7,
                            Balance = 7595m,
                            Email = "jennifer_mitchell@email.com",
                            Username = "jennifermitchell861"
                        },
                        new
                        {
                            AccountNumber = 8,
                            Balance = 4974m,
                            Email = "jennifer_mitchell@email.com",
                            Username = "jennifermitchell861"
                        },
                        new
                        {
                            AccountNumber = 9,
                            Balance = 4191m,
                            Email = "jennifer_mitchell@email.com",
                            Username = "jennifermitchell861"
                        },
                        new
                        {
                            AccountNumber = 10,
                            Balance = 2569m,
                            Email = "william_parker@email.com",
                            Username = "williamparker667"
                        },
                        new
                        {
                            AccountNumber = 11,
                            Balance = 3763m,
                            Email = "william_parker@email.com",
                            Username = "williamparker667"
                        },
                        new
                        {
                            AccountNumber = 12,
                            Balance = 7006m,
                            Email = "linda_carter@email.com",
                            Username = "lindacarter752"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN ('Deposit','Withdraw')");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = 1,
                            Amount = 284m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = 1,
                            Amount = 19m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountNumber = 1,
                            Amount = 449m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountNumber = 1,
                            Amount = 973m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountNumber = 1,
                            Amount = 977m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountNumber = 2,
                            Amount = 313m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountNumber = 2,
                            Amount = 21m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountNumber = 2,
                            Amount = 697m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountNumber = 2,
                            Amount = 781m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountNumber = 2,
                            Amount = 812m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountNumber = 2,
                            Amount = 175m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountNumber = 2,
                            Amount = 545m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountNumber = 2,
                            Amount = 287m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountNumber = 2,
                            Amount = 963m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountNumber = 3,
                            Amount = 709m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountNumber = 3,
                            Amount = 667m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountNumber = 3,
                            Amount = 337m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountNumber = 3,
                            Amount = 33m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountNumber = 3,
                            Amount = 650m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountNumber = 3,
                            Amount = 471m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountNumber = 4,
                            Amount = 996m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountNumber = 4,
                            Amount = 647m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountNumber = 4,
                            Amount = 902m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountNumber = 4,
                            Amount = 837m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountNumber = 4,
                            Amount = 165m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountNumber = 5,
                            Amount = 244m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 27,
                            AccountNumber = 5,
                            Amount = 404m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 28,
                            AccountNumber = 5,
                            Amount = 380m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 29,
                            AccountNumber = 5,
                            Amount = 846m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 30,
                            AccountNumber = 5,
                            Amount = 12m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 31,
                            AccountNumber = 5,
                            Amount = 52m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 32,
                            AccountNumber = 5,
                            Amount = 387m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 33,
                            AccountNumber = 5,
                            Amount = 717m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 34,
                            AccountNumber = 5,
                            Amount = 994m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 35,
                            AccountNumber = 5,
                            Amount = 470m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 36,
                            AccountNumber = 6,
                            Amount = 272m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 37,
                            AccountNumber = 6,
                            Amount = 996m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 38,
                            AccountNumber = 6,
                            Amount = 834m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 39,
                            AccountNumber = 6,
                            Amount = 175m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 40,
                            AccountNumber = 6,
                            Amount = 342m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 41,
                            AccountNumber = 6,
                            Amount = 80m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 42,
                            AccountNumber = 6,
                            Amount = 170m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 43,
                            AccountNumber = 7,
                            Amount = 859m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 44,
                            AccountNumber = 7,
                            Amount = 487m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 45,
                            AccountNumber = 7,
                            Amount = 139m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 46,
                            AccountNumber = 7,
                            Amount = 29m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 47,
                            AccountNumber = 7,
                            Amount = 804m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 48,
                            AccountNumber = 7,
                            Amount = 934m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 49,
                            AccountNumber = 7,
                            Amount = 622m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 50,
                            AccountNumber = 7,
                            Amount = 307m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 51,
                            AccountNumber = 8,
                            Amount = 644m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 52,
                            AccountNumber = 8,
                            Amount = 930m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 53,
                            AccountNumber = 9,
                            Amount = 183m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 54,
                            AccountNumber = 9,
                            Amount = 682m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 55,
                            AccountNumber = 9,
                            Amount = 981m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 56,
                            AccountNumber = 9,
                            Amount = 323m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 57,
                            AccountNumber = 9,
                            Amount = 271m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 58,
                            AccountNumber = 9,
                            Amount = 804m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 59,
                            AccountNumber = 9,
                            Amount = 834m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 60,
                            AccountNumber = 9,
                            Amount = 200m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 61,
                            AccountNumber = 9,
                            Amount = 516m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 62,
                            AccountNumber = 9,
                            Amount = 551m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 63,
                            AccountNumber = 10,
                            Amount = 573m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 64,
                            AccountNumber = 10,
                            Amount = 159m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 65,
                            AccountNumber = 10,
                            Amount = 21m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 66,
                            AccountNumber = 10,
                            Amount = 27m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 67,
                            AccountNumber = 10,
                            Amount = 722m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 68,
                            AccountNumber = 10,
                            Amount = 705m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 69,
                            AccountNumber = 10,
                            Amount = 35m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 70,
                            AccountNumber = 10,
                            Amount = 222m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 71,
                            AccountNumber = 10,
                            Amount = 755m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 72,
                            AccountNumber = 11,
                            Amount = 691m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 73,
                            AccountNumber = 11,
                            Amount = 924m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 74,
                            AccountNumber = 11,
                            Amount = 580m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 75,
                            AccountNumber = 11,
                            Amount = 891m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 76,
                            AccountNumber = 12,
                            Amount = 128m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 77,
                            AccountNumber = 12,
                            Amount = 539m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 78,
                            AccountNumber = 12,
                            Amount = 593m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 79,
                            AccountNumber = 12,
                            Amount = 469m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 80,
                            AccountNumber = 12,
                            Amount = 267m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 81,
                            AccountNumber = 12,
                            Amount = 588m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 82,
                            AccountNumber = 12,
                            Amount = 279m,
                            Type = "Withdraw"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Username = "jamescollins161",
                            Address = "2 Collins Street, City 3",
                            Email = "james_collins@email.com",
                            Password = "pass8675",
                            Phone = "0479061052",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\2.jpg"
                        },
                        new
                        {
                            Username = "lindareyes715",
                            Address = "155 Reyes Street, City 9",
                            Email = "linda_reyes@email.com",
                            Password = "pass1831",
                            Phone = "0430220024",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\4.jpg"
                        },
                        new
                        {
                            Username = "jennifermitchell861",
                            Address = "14 Mitchell Street, City 5",
                            Email = "jennifer_mitchell@email.com",
                            Password = "pass5866",
                            Phone = "0455686560",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        },
                        new
                        {
                            Username = "williamparker667",
                            Address = "42 Parker Street, City 7",
                            Email = "william_parker@email.com",
                            Password = "pass9784",
                            Phone = "0493662132",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        },
                        new
                        {
                            Username = "lindacarter752",
                            Address = "134 Carter Street, City 3",
                            Email = "linda_carter@email.com",
                            Password = "pass1429",
                            Phone = "0492784652",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.HasOne("BankWebService.Models.UserProfile", "UserProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankWebService.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
