// <auto-generated />
using BankWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251017081748_SeedRefresh")]
    partial class SeedRefresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.HasIndex("Username");

                    b.ToTable("Bank_Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            Balance = 1268m,
                            Email = "james_flores@email.com",
                            Username = "jamesflores126"
                        },
                        new
                        {
                            AccountNumber = 2,
                            Balance = 2955m,
                            Email = "james_flores@email.com",
                            Username = "jamesflores126"
                        },
                        new
                        {
                            AccountNumber = 3,
                            Balance = 7626m,
                            Email = "james_flores@email.com",
                            Username = "jamesflores126"
                        },
                        new
                        {
                            AccountNumber = 4,
                            Balance = 8586m,
                            Email = "james_flores@email.com",
                            Username = "jamesflores126"
                        },
                        new
                        {
                            AccountNumber = 5,
                            Balance = 2282m,
                            Email = "james_flores@email.com",
                            Username = "jamesflores126"
                        },
                        new
                        {
                            AccountNumber = 6,
                            Balance = 8313m,
                            Email = "james_flores@email.com",
                            Username = "jamesflores126"
                        },
                        new
                        {
                            AccountNumber = 7,
                            Balance = 3545m,
                            Email = "christopher_mitchell@email.com",
                            Username = "christophermitchell236"
                        },
                        new
                        {
                            AccountNumber = 8,
                            Balance = 2867m,
                            Email = "christopher_mitchell@email.com",
                            Username = "christophermitchell236"
                        },
                        new
                        {
                            AccountNumber = 9,
                            Balance = 1922m,
                            Email = "christopher_mitchell@email.com",
                            Username = "christophermitchell236"
                        },
                        new
                        {
                            AccountNumber = 10,
                            Balance = 5569m,
                            Email = "christopher_mitchell@email.com",
                            Username = "christophermitchell236"
                        },
                        new
                        {
                            AccountNumber = 11,
                            Balance = 6332m,
                            Email = "christopher_mitchell@email.com",
                            Username = "christophermitchell236"
                        },
                        new
                        {
                            AccountNumber = 12,
                            Balance = 2942m,
                            Email = "christopher_mitchell@email.com",
                            Username = "christophermitchell236"
                        },
                        new
                        {
                            AccountNumber = 13,
                            Balance = 8952m,
                            Email = "christopher_mitchell@email.com",
                            Username = "christophermitchell236"
                        },
                        new
                        {
                            AccountNumber = 14,
                            Balance = 1205m,
                            Email = "susan_carter@email.com",
                            Username = "susancarter357"
                        },
                        new
                        {
                            AccountNumber = 15,
                            Balance = 3906m,
                            Email = "susan_carter@email.com",
                            Username = "susancarter357"
                        },
                        new
                        {
                            AccountNumber = 16,
                            Balance = 5831m,
                            Email = "susan_carter@email.com",
                            Username = "susancarter357"
                        },
                        new
                        {
                            AccountNumber = 17,
                            Balance = 6566m,
                            Email = "elizabeth_evans@email.com",
                            Username = "elizabethevans368"
                        },
                        new
                        {
                            AccountNumber = 18,
                            Balance = 9461m,
                            Email = "elizabeth_evans@email.com",
                            Username = "elizabethevans368"
                        },
                        new
                        {
                            AccountNumber = 19,
                            Balance = 3989m,
                            Email = "elizabeth_evans@email.com",
                            Username = "elizabethevans368"
                        },
                        new
                        {
                            AccountNumber = 20,
                            Balance = 8823m,
                            Email = "elizabeth_evans@email.com",
                            Username = "elizabethevans368"
                        },
                        new
                        {
                            AccountNumber = 21,
                            Balance = 5161m,
                            Email = "elizabeth_evans@email.com",
                            Username = "elizabethevans368"
                        },
                        new
                        {
                            AccountNumber = 22,
                            Balance = 419m,
                            Email = "elizabeth_evans@email.com",
                            Username = "elizabethevans368"
                        },
                        new
                        {
                            AccountNumber = 23,
                            Balance = 5985m,
                            Email = "elizabeth_evans@email.com",
                            Username = "elizabethevans368"
                        },
                        new
                        {
                            AccountNumber = 24,
                            Balance = 4281m,
                            Email = "barbara_green@email.com",
                            Username = "barbaragreen251"
                        },
                        new
                        {
                            AccountNumber = 25,
                            Balance = 8194m,
                            Email = "barbara_green@email.com",
                            Username = "barbaragreen251"
                        },
                        new
                        {
                            AccountNumber = 26,
                            Balance = 9657m,
                            Email = "barbara_green@email.com",
                            Username = "barbaragreen251"
                        },
                        new
                        {
                            AccountNumber = 27,
                            Balance = 8974m,
                            Email = "linda_carter@email.com",
                            Username = "lindacarter117"
                        },
                        new
                        {
                            AccountNumber = 28,
                            Balance = 7123m,
                            Email = "linda_carter@email.com",
                            Username = "lindacarter117"
                        },
                        new
                        {
                            AccountNumber = 29,
                            Balance = 7115m,
                            Email = "linda_carter@email.com",
                            Username = "lindacarter117"
                        },
                        new
                        {
                            AccountNumber = 30,
                            Balance = 9166m,
                            Email = "linda_carter@email.com",
                            Username = "lindacarter117"
                        },
                        new
                        {
                            AccountNumber = 31,
                            Balance = 184m,
                            Email = "linda_carter@email.com",
                            Username = "lindacarter117"
                        },
                        new
                        {
                            AccountNumber = 32,
                            Balance = 4528m,
                            Email = "linda_carter@email.com",
                            Username = "lindacarter117"
                        },
                        new
                        {
                            AccountNumber = 33,
                            Balance = 7597m,
                            Email = "linda_carter@email.com",
                            Username = "lindacarter117"
                        },
                        new
                        {
                            AccountNumber = 34,
                            Balance = 1563m,
                            Email = "linda_carter@email.com",
                            Username = "lindacarter117"
                        },
                        new
                        {
                            AccountNumber = 35,
                            Balance = 2618m,
                            Email = "richard_parker@email.com",
                            Username = "richardparker167"
                        },
                        new
                        {
                            AccountNumber = 36,
                            Balance = 4588m,
                            Email = "richard_parker@email.com",
                            Username = "richardparker167"
                        },
                        new
                        {
                            AccountNumber = 37,
                            Balance = 9321m,
                            Email = "richard_parker@email.com",
                            Username = "richardparker167"
                        },
                        new
                        {
                            AccountNumber = 38,
                            Balance = 2486m,
                            Email = "richard_parker@email.com",
                            Username = "richardparker167"
                        },
                        new
                        {
                            AccountNumber = 39,
                            Balance = 6264m,
                            Email = "richard_parker@email.com",
                            Username = "richardparker167"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN ('Deposit','Withdraw')");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = 1,
                            Amount = 490m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = 2,
                            Amount = 499m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountNumber = 2,
                            Amount = 539m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountNumber = 2,
                            Amount = 101m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountNumber = 2,
                            Amount = 272m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountNumber = 2,
                            Amount = 291m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountNumber = 2,
                            Amount = 15m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountNumber = 3,
                            Amount = 221m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountNumber = 3,
                            Amount = 468m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountNumber = 3,
                            Amount = 450m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountNumber = 3,
                            Amount = 588m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountNumber = 3,
                            Amount = 521m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountNumber = 3,
                            Amount = 708m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountNumber = 4,
                            Amount = 670m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountNumber = 4,
                            Amount = 923m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountNumber = 4,
                            Amount = 799m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountNumber = 4,
                            Amount = 827m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountNumber = 4,
                            Amount = 939m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountNumber = 4,
                            Amount = 89m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountNumber = 4,
                            Amount = 16m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountNumber = 4,
                            Amount = 922m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountNumber = 4,
                            Amount = 717m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountNumber = 5,
                            Amount = 701m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountNumber = 5,
                            Amount = 634m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountNumber = 5,
                            Amount = 661m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountNumber = 5,
                            Amount = 698m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 27,
                            AccountNumber = 5,
                            Amount = 247m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 28,
                            AccountNumber = 5,
                            Amount = 924m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 29,
                            AccountNumber = 6,
                            Amount = 318m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 30,
                            AccountNumber = 6,
                            Amount = 473m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 31,
                            AccountNumber = 6,
                            Amount = 282m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 32,
                            AccountNumber = 6,
                            Amount = 990m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 33,
                            AccountNumber = 6,
                            Amount = 213m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 34,
                            AccountNumber = 6,
                            Amount = 880m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 35,
                            AccountNumber = 7,
                            Amount = 520m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 36,
                            AccountNumber = 7,
                            Amount = 702m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 37,
                            AccountNumber = 7,
                            Amount = 384m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 38,
                            AccountNumber = 7,
                            Amount = 493m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 39,
                            AccountNumber = 7,
                            Amount = 841m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 40,
                            AccountNumber = 8,
                            Amount = 144m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 41,
                            AccountNumber = 8,
                            Amount = 133m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 42,
                            AccountNumber = 8,
                            Amount = 766m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 43,
                            AccountNumber = 8,
                            Amount = 102m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 44,
                            AccountNumber = 8,
                            Amount = 364m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 45,
                            AccountNumber = 8,
                            Amount = 663m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 46,
                            AccountNumber = 9,
                            Amount = 149m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 47,
                            AccountNumber = 9,
                            Amount = 542m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 48,
                            AccountNumber = 9,
                            Amount = 24m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 49,
                            AccountNumber = 10,
                            Amount = 548m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 50,
                            AccountNumber = 10,
                            Amount = 929m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 51,
                            AccountNumber = 10,
                            Amount = 661m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 52,
                            AccountNumber = 10,
                            Amount = 407m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 53,
                            AccountNumber = 10,
                            Amount = 76m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 54,
                            AccountNumber = 10,
                            Amount = 533m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 55,
                            AccountNumber = 10,
                            Amount = 695m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 56,
                            AccountNumber = 10,
                            Amount = 241m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 57,
                            AccountNumber = 10,
                            Amount = 63m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 58,
                            AccountNumber = 11,
                            Amount = 614m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 59,
                            AccountNumber = 11,
                            Amount = 972m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 60,
                            AccountNumber = 11,
                            Amount = 604m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 61,
                            AccountNumber = 12,
                            Amount = 210m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 62,
                            AccountNumber = 13,
                            Amount = 940m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 63,
                            AccountNumber = 14,
                            Amount = 433m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 64,
                            AccountNumber = 14,
                            Amount = 224m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 65,
                            AccountNumber = 14,
                            Amount = 639m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 66,
                            AccountNumber = 14,
                            Amount = 185m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 67,
                            AccountNumber = 14,
                            Amount = 723m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 68,
                            AccountNumber = 14,
                            Amount = 872m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 69,
                            AccountNumber = 14,
                            Amount = 949m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 70,
                            AccountNumber = 14,
                            Amount = 313m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 71,
                            AccountNumber = 15,
                            Amount = 647m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 72,
                            AccountNumber = 15,
                            Amount = 168m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 73,
                            AccountNumber = 16,
                            Amount = 225m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 74,
                            AccountNumber = 16,
                            Amount = 747m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 75,
                            AccountNumber = 16,
                            Amount = 259m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 76,
                            AccountNumber = 16,
                            Amount = 397m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 77,
                            AccountNumber = 16,
                            Amount = 65m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 78,
                            AccountNumber = 16,
                            Amount = 973m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 79,
                            AccountNumber = 17,
                            Amount = 809m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 80,
                            AccountNumber = 17,
                            Amount = 405m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 81,
                            AccountNumber = 17,
                            Amount = 810m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 82,
                            AccountNumber = 17,
                            Amount = 874m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 83,
                            AccountNumber = 17,
                            Amount = 22m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 84,
                            AccountNumber = 17,
                            Amount = 863m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 85,
                            AccountNumber = 18,
                            Amount = 372m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 86,
                            AccountNumber = 18,
                            Amount = 168m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 87,
                            AccountNumber = 18,
                            Amount = 428m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 88,
                            AccountNumber = 19,
                            Amount = 332m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 89,
                            AccountNumber = 20,
                            Amount = 757m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 90,
                            AccountNumber = 20,
                            Amount = 877m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 91,
                            AccountNumber = 20,
                            Amount = 976m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 92,
                            AccountNumber = 20,
                            Amount = 64m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 93,
                            AccountNumber = 20,
                            Amount = 84m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 94,
                            AccountNumber = 20,
                            Amount = 517m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 95,
                            AccountNumber = 20,
                            Amount = 600m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 96,
                            AccountNumber = 21,
                            Amount = 200m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 97,
                            AccountNumber = 21,
                            Amount = 871m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 98,
                            AccountNumber = 21,
                            Amount = 856m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 99,
                            AccountNumber = 21,
                            Amount = 956m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 100,
                            AccountNumber = 22,
                            Amount = 716m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 101,
                            AccountNumber = 22,
                            Amount = 892m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 102,
                            AccountNumber = 22,
                            Amount = 494m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 103,
                            AccountNumber = 22,
                            Amount = 29m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 104,
                            AccountNumber = 22,
                            Amount = 487m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 105,
                            AccountNumber = 22,
                            Amount = 955m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 106,
                            AccountNumber = 23,
                            Amount = 733m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 107,
                            AccountNumber = 23,
                            Amount = 118m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 108,
                            AccountNumber = 23,
                            Amount = 548m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 109,
                            AccountNumber = 24,
                            Amount = 664m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 110,
                            AccountNumber = 24,
                            Amount = 706m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 111,
                            AccountNumber = 24,
                            Amount = 341m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 112,
                            AccountNumber = 24,
                            Amount = 547m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 113,
                            AccountNumber = 24,
                            Amount = 337m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 114,
                            AccountNumber = 24,
                            Amount = 262m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 115,
                            AccountNumber = 24,
                            Amount = 761m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 116,
                            AccountNumber = 25,
                            Amount = 214m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 117,
                            AccountNumber = 25,
                            Amount = 265m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 118,
                            AccountNumber = 25,
                            Amount = 689m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 119,
                            AccountNumber = 26,
                            Amount = 460m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 120,
                            AccountNumber = 26,
                            Amount = 824m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 121,
                            AccountNumber = 26,
                            Amount = 535m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 122,
                            AccountNumber = 27,
                            Amount = 815m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 123,
                            AccountNumber = 27,
                            Amount = 306m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 124,
                            AccountNumber = 28,
                            Amount = 235m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 125,
                            AccountNumber = 28,
                            Amount = 449m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 126,
                            AccountNumber = 28,
                            Amount = 638m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 127,
                            AccountNumber = 28,
                            Amount = 969m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 128,
                            AccountNumber = 28,
                            Amount = 761m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 129,
                            AccountNumber = 29,
                            Amount = 946m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 130,
                            AccountNumber = 29,
                            Amount = 613m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 131,
                            AccountNumber = 29,
                            Amount = 305m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 132,
                            AccountNumber = 29,
                            Amount = 23m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 133,
                            AccountNumber = 30,
                            Amount = 154m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 134,
                            AccountNumber = 30,
                            Amount = 190m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 135,
                            AccountNumber = 30,
                            Amount = 935m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 136,
                            AccountNumber = 30,
                            Amount = 781m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 137,
                            AccountNumber = 30,
                            Amount = 546m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 138,
                            AccountNumber = 31,
                            Amount = 943m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 139,
                            AccountNumber = 31,
                            Amount = 800m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 140,
                            AccountNumber = 31,
                            Amount = 386m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 141,
                            AccountNumber = 31,
                            Amount = 304m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 142,
                            AccountNumber = 31,
                            Amount = 633m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 143,
                            AccountNumber = 31,
                            Amount = 518m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 144,
                            AccountNumber = 31,
                            Amount = 233m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 145,
                            AccountNumber = 32,
                            Amount = 848m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 146,
                            AccountNumber = 32,
                            Amount = 83m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 147,
                            AccountNumber = 32,
                            Amount = 18m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 148,
                            AccountNumber = 32,
                            Amount = 50m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 149,
                            AccountNumber = 32,
                            Amount = 388m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 150,
                            AccountNumber = 32,
                            Amount = 352m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 151,
                            AccountNumber = 32,
                            Amount = 29m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 152,
                            AccountNumber = 32,
                            Amount = 727m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 153,
                            AccountNumber = 33,
                            Amount = 630m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 154,
                            AccountNumber = 33,
                            Amount = 65m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 155,
                            AccountNumber = 33,
                            Amount = 458m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 156,
                            AccountNumber = 33,
                            Amount = 290m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 157,
                            AccountNumber = 33,
                            Amount = 780m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 158,
                            AccountNumber = 33,
                            Amount = 668m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 159,
                            AccountNumber = 33,
                            Amount = 92m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 160,
                            AccountNumber = 33,
                            Amount = 597m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 161,
                            AccountNumber = 33,
                            Amount = 959m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 162,
                            AccountNumber = 34,
                            Amount = 286m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 163,
                            AccountNumber = 34,
                            Amount = 668m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 164,
                            AccountNumber = 34,
                            Amount = 841m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 165,
                            AccountNumber = 34,
                            Amount = 557m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 166,
                            AccountNumber = 34,
                            Amount = 116m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 167,
                            AccountNumber = 35,
                            Amount = 313m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 168,
                            AccountNumber = 35,
                            Amount = 493m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 169,
                            AccountNumber = 35,
                            Amount = 491m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 170,
                            AccountNumber = 35,
                            Amount = 776m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 171,
                            AccountNumber = 36,
                            Amount = 509m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 172,
                            AccountNumber = 36,
                            Amount = 102m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 173,
                            AccountNumber = 37,
                            Amount = 984m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 174,
                            AccountNumber = 37,
                            Amount = 604m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 175,
                            AccountNumber = 37,
                            Amount = 718m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 176,
                            AccountNumber = 37,
                            Amount = 22m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 177,
                            AccountNumber = 37,
                            Amount = 488m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 178,
                            AccountNumber = 37,
                            Amount = 334m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 179,
                            AccountNumber = 37,
                            Amount = 784m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 180,
                            AccountNumber = 37,
                            Amount = 33m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 181,
                            AccountNumber = 37,
                            Amount = 404m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 182,
                            AccountNumber = 38,
                            Amount = 95m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 183,
                            AccountNumber = 38,
                            Amount = 168m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 184,
                            AccountNumber = 38,
                            Amount = 736m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 185,
                            AccountNumber = 38,
                            Amount = 714m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 186,
                            AccountNumber = 38,
                            Amount = 248m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 187,
                            AccountNumber = 38,
                            Amount = 385m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 188,
                            AccountNumber = 39,
                            Amount = 492m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 189,
                            AccountNumber = 39,
                            Amount = 36m,
                            Type = "Deposit"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Username = "jamesflores126",
                            Address = "43 Flores Street, City 1",
                            Email = "james_flores@email.com",
                            Password = "pass1713",
                            Phone = "0444380740",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "christophermitchell236",
                            Address = "72 Mitchell Street, City 1",
                            Email = "christopher_mitchell@email.com",
                            Password = "pass2229",
                            Phone = "0462995421",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\4.jpg"
                        },
                        new
                        {
                            Username = "susancarter357",
                            Address = "96 Carter Street, City 1",
                            Email = "susan_carter@email.com",
                            Password = "pass7469",
                            Phone = "0452067754",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\2.jpg"
                        },
                        new
                        {
                            Username = "elizabethevans368",
                            Address = "106 Evans Street, City 8",
                            Email = "elizabeth_evans@email.com",
                            Password = "pass9791",
                            Phone = "0495949095",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "barbaragreen251",
                            Address = "96 Green Street, City 8",
                            Email = "barbara_green@email.com",
                            Password = "pass7672",
                            Phone = "0461899010",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "lindacarter117",
                            Address = "72 Carter Street, City 1",
                            Email = "linda_carter@email.com",
                            Password = "pass8561",
                            Phone = "0478173708",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "richardparker167",
                            Address = "79 Parker Street, City 8",
                            Email = "richard_parker@email.com",
                            Password = "pass2200",
                            Phone = "0427307348",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "BankAdmin",
                            Address = "Head Office",
                            Email = "admin@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "MoeDegrasse",
                            Address = "17 Harper Street, City 2",
                            Email = "MoeDegrasse@email.com",
                            Password = "pass12",
                            Phone = "0444122322",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.HasOne("BankWebService.Models.UserProfile", "UserProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankWebService.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
