// <auto-generated />
using BankWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251018085841_SeedRefresh")]
    partial class SeedRefresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.HasIndex("Username");

                    b.ToTable("Bank_Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            Balance = 8863m,
                            Email = "jessica_campbell@email.com",
                            Name = "Jessica's Account 1",
                            Username = "jessicacampbell185"
                        },
                        new
                        {
                            AccountNumber = 2,
                            Balance = 7353m,
                            Email = "jessica_campbell@email.com",
                            Name = "Jessica's Account 2",
                            Username = "jessicacampbell185"
                        },
                        new
                        {
                            AccountNumber = 3,
                            Balance = 5147m,
                            Email = "jessica_campbell@email.com",
                            Name = "Jessica's Account 3",
                            Username = "jessicacampbell185"
                        },
                        new
                        {
                            AccountNumber = 4,
                            Balance = 2900m,
                            Email = "jessica_campbell@email.com",
                            Name = "Jessica's Account 4",
                            Username = "jessicacampbell185"
                        },
                        new
                        {
                            AccountNumber = 5,
                            Balance = 2064m,
                            Email = "james_diaz@email.com",
                            Name = "James's Account 1",
                            Username = "jamesdiaz996"
                        },
                        new
                        {
                            AccountNumber = 6,
                            Balance = 4756m,
                            Email = "james_diaz@email.com",
                            Name = "James's Account 2",
                            Username = "jamesdiaz996"
                        },
                        new
                        {
                            AccountNumber = 7,
                            Balance = 5408m,
                            Email = "james_diaz@email.com",
                            Name = "James's Account 3",
                            Username = "jamesdiaz996"
                        },
                        new
                        {
                            AccountNumber = 8,
                            Balance = 6580m,
                            Email = "sarah_diaz@email.com",
                            Name = "Sarah's Account 1",
                            Username = "sarahdiaz655"
                        },
                        new
                        {
                            AccountNumber = 9,
                            Balance = 1821m,
                            Email = "sarah_diaz@email.com",
                            Name = "Sarah's Account 2",
                            Username = "sarahdiaz655"
                        },
                        new
                        {
                            AccountNumber = 10,
                            Balance = 8267m,
                            Email = "sarah_diaz@email.com",
                            Name = "Sarah's Account 3",
                            Username = "sarahdiaz655"
                        },
                        new
                        {
                            AccountNumber = 11,
                            Balance = 7663m,
                            Email = "jennifer_roberts@email.com",
                            Name = "Jennifer's Account 1",
                            Username = "jenniferroberts143"
                        },
                        new
                        {
                            AccountNumber = 12,
                            Balance = 7236m,
                            Email = "richard_hall@email.com",
                            Name = "Richard's Account 1",
                            Username = "richardhall302"
                        },
                        new
                        {
                            AccountNumber = 13,
                            Balance = 1833m,
                            Email = "richard_hall@email.com",
                            Name = "Richard's Account 2",
                            Username = "richardhall302"
                        },
                        new
                        {
                            AccountNumber = 14,
                            Balance = 518m,
                            Email = "richard_hall@email.com",
                            Name = "Richard's Account 3",
                            Username = "richardhall302"
                        },
                        new
                        {
                            AccountNumber = 15,
                            Balance = 1891m,
                            Email = "richard_hall@email.com",
                            Name = "Richard's Account 4",
                            Username = "richardhall302"
                        },
                        new
                        {
                            AccountNumber = 16,
                            Balance = 5837m,
                            Email = "richard_hall@email.com",
                            Name = "Richard's Account 5",
                            Username = "richardhall302"
                        },
                        new
                        {
                            AccountNumber = 17,
                            Balance = 8716m,
                            Email = "mary_hall@email.com",
                            Name = "Mary's Account 1",
                            Username = "maryhall268"
                        },
                        new
                        {
                            AccountNumber = 18,
                            Balance = 9141m,
                            Email = "mary_hall@email.com",
                            Name = "Mary's Account 2",
                            Username = "maryhall268"
                        },
                        new
                        {
                            AccountNumber = 19,
                            Balance = 1522m,
                            Email = "mary_hall@email.com",
                            Name = "Mary's Account 3",
                            Username = "maryhall268"
                        },
                        new
                        {
                            AccountNumber = 20,
                            Balance = 1779m,
                            Email = "barbara_parker@email.com",
                            Name = "Barbara's Account 1",
                            Username = "barbaraparker204"
                        },
                        new
                        {
                            AccountNumber = 21,
                            Balance = 5507m,
                            Email = "barbara_parker@email.com",
                            Name = "Barbara's Account 2",
                            Username = "barbaraparker204"
                        },
                        new
                        {
                            AccountNumber = 22,
                            Balance = 2384m,
                            Email = "barbara_parker@email.com",
                            Name = "Barbara's Account 3",
                            Username = "barbaraparker204"
                        },
                        new
                        {
                            AccountNumber = 23,
                            Balance = 7834m,
                            Email = "barbara_parker@email.com",
                            Name = "Barbara's Account 4",
                            Username = "barbaraparker204"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN ('Deposit','Withdraw')");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = 1,
                            Amount = 88m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = 1,
                            Amount = 510m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountNumber = 1,
                            Amount = 402m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountNumber = 2,
                            Amount = 188m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountNumber = 2,
                            Amount = 944m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountNumber = 2,
                            Amount = 773m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountNumber = 2,
                            Amount = 100m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountNumber = 2,
                            Amount = 152m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountNumber = 2,
                            Amount = 996m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountNumber = 2,
                            Amount = 377m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountNumber = 2,
                            Amount = 438m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountNumber = 2,
                            Amount = 67m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountNumber = 2,
                            Amount = 395m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountNumber = 3,
                            Amount = 126m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountNumber = 3,
                            Amount = 280m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountNumber = 4,
                            Amount = 786m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountNumber = 4,
                            Amount = 218m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountNumber = 4,
                            Amount = 646m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountNumber = 4,
                            Amount = 276m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountNumber = 4,
                            Amount = 798m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountNumber = 4,
                            Amount = 49m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountNumber = 4,
                            Amount = 476m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountNumber = 4,
                            Amount = 144m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountNumber = 4,
                            Amount = 915m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountNumber = 4,
                            Amount = 936m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountNumber = 4,
                            Amount = 524m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 27,
                            AccountNumber = 5,
                            Amount = 640m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 28,
                            AccountNumber = 5,
                            Amount = 959m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 29,
                            AccountNumber = 5,
                            Amount = 208m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 30,
                            AccountNumber = 5,
                            Amount = 284m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 31,
                            AccountNumber = 5,
                            Amount = 362m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 32,
                            AccountNumber = 5,
                            Amount = 893m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 33,
                            AccountNumber = 5,
                            Amount = 463m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 34,
                            AccountNumber = 5,
                            Amount = 447m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 35,
                            AccountNumber = 5,
                            Amount = 476m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 36,
                            AccountNumber = 5,
                            Amount = 958m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 37,
                            AccountNumber = 5,
                            Amount = 474m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 38,
                            AccountNumber = 6,
                            Amount = 418m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 39,
                            AccountNumber = 6,
                            Amount = 676m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 40,
                            AccountNumber = 6,
                            Amount = 555m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 41,
                            AccountNumber = 6,
                            Amount = 513m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 42,
                            AccountNumber = 6,
                            Amount = 220m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 43,
                            AccountNumber = 6,
                            Amount = 283m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 44,
                            AccountNumber = 6,
                            Amount = 729m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 45,
                            AccountNumber = 7,
                            Amount = 193m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 46,
                            AccountNumber = 7,
                            Amount = 371m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 47,
                            AccountNumber = 7,
                            Amount = 43m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 48,
                            AccountNumber = 7,
                            Amount = 854m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 49,
                            AccountNumber = 7,
                            Amount = 523m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 50,
                            AccountNumber = 7,
                            Amount = 774m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 51,
                            AccountNumber = 7,
                            Amount = 632m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 52,
                            AccountNumber = 7,
                            Amount = 594m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 53,
                            AccountNumber = 7,
                            Amount = 562m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 54,
                            AccountNumber = 7,
                            Amount = 790m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 55,
                            AccountNumber = 7,
                            Amount = 547m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 56,
                            AccountNumber = 7,
                            Amount = 576m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 57,
                            AccountNumber = 8,
                            Amount = 968m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 58,
                            AccountNumber = 8,
                            Amount = 737m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 59,
                            AccountNumber = 8,
                            Amount = 223m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 60,
                            AccountNumber = 8,
                            Amount = 301m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 61,
                            AccountNumber = 8,
                            Amount = 430m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 62,
                            AccountNumber = 9,
                            Amount = 415m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 63,
                            AccountNumber = 10,
                            Amount = 414m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 64,
                            AccountNumber = 10,
                            Amount = 585m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 65,
                            AccountNumber = 10,
                            Amount = 343m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 66,
                            AccountNumber = 10,
                            Amount = 949m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 67,
                            AccountNumber = 10,
                            Amount = 802m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 68,
                            AccountNumber = 11,
                            Amount = 620m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 69,
                            AccountNumber = 11,
                            Amount = 501m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 70,
                            AccountNumber = 11,
                            Amount = 400m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 71,
                            AccountNumber = 11,
                            Amount = 724m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 72,
                            AccountNumber = 11,
                            Amount = 866m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 73,
                            AccountNumber = 12,
                            Amount = 665m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 74,
                            AccountNumber = 12,
                            Amount = 388m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 75,
                            AccountNumber = 12,
                            Amount = 782m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 76,
                            AccountNumber = 12,
                            Amount = 432m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 77,
                            AccountNumber = 12,
                            Amount = 927m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 78,
                            AccountNumber = 12,
                            Amount = 951m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 79,
                            AccountNumber = 12,
                            Amount = 582m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 80,
                            AccountNumber = 12,
                            Amount = 97m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 81,
                            AccountNumber = 12,
                            Amount = 537m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 82,
                            AccountNumber = 13,
                            Amount = 487m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 83,
                            AccountNumber = 13,
                            Amount = 734m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 84,
                            AccountNumber = 13,
                            Amount = 32m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 85,
                            AccountNumber = 13,
                            Amount = 301m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 86,
                            AccountNumber = 13,
                            Amount = 334m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 87,
                            AccountNumber = 13,
                            Amount = 416m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 88,
                            AccountNumber = 13,
                            Amount = 597m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 89,
                            AccountNumber = 13,
                            Amount = 128m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 90,
                            AccountNumber = 14,
                            Amount = 181m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 91,
                            AccountNumber = 14,
                            Amount = 203m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 92,
                            AccountNumber = 14,
                            Amount = 755m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 93,
                            AccountNumber = 14,
                            Amount = 489m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 94,
                            AccountNumber = 14,
                            Amount = 210m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 95,
                            AccountNumber = 14,
                            Amount = 411m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 96,
                            AccountNumber = 14,
                            Amount = 663m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 97,
                            AccountNumber = 14,
                            Amount = 959m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 98,
                            AccountNumber = 14,
                            Amount = 877m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 99,
                            AccountNumber = 14,
                            Amount = 646m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 100,
                            AccountNumber = 15,
                            Amount = 662m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 101,
                            AccountNumber = 15,
                            Amount = 678m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 102,
                            AccountNumber = 16,
                            Amount = 922m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 103,
                            AccountNumber = 17,
                            Amount = 543m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 104,
                            AccountNumber = 18,
                            Amount = 338m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 105,
                            AccountNumber = 19,
                            Amount = 844m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 106,
                            AccountNumber = 19,
                            Amount = 487m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 107,
                            AccountNumber = 19,
                            Amount = 281m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 108,
                            AccountNumber = 20,
                            Amount = 600m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 109,
                            AccountNumber = 20,
                            Amount = 346m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 110,
                            AccountNumber = 20,
                            Amount = 991m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 111,
                            AccountNumber = 20,
                            Amount = 910m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 112,
                            AccountNumber = 20,
                            Amount = 639m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 113,
                            AccountNumber = 20,
                            Amount = 843m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 114,
                            AccountNumber = 20,
                            Amount = 958m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 115,
                            AccountNumber = 20,
                            Amount = 752m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 116,
                            AccountNumber = 20,
                            Amount = 747m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 117,
                            AccountNumber = 21,
                            Amount = 175m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 118,
                            AccountNumber = 21,
                            Amount = 357m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 119,
                            AccountNumber = 21,
                            Amount = 568m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 120,
                            AccountNumber = 22,
                            Amount = 243m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 121,
                            AccountNumber = 22,
                            Amount = 989m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 122,
                            AccountNumber = 23,
                            Amount = 10m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 123,
                            AccountNumber = 23,
                            Amount = 760m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 124,
                            AccountNumber = 23,
                            Amount = 777m,
                            Type = "Withdraw"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Username = "jessicacampbell185",
                            Address = "164 Campbell Street, City 5",
                            Email = "jessica_campbell@email.com",
                            Password = "pass8105",
                            Phone = "0451200149",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "jamesdiaz996",
                            Address = "175 Diaz Street, City 1",
                            Email = "james_diaz@email.com",
                            Password = "pass9547",
                            Phone = "0499003707",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "sarahdiaz655",
                            Address = "110 Diaz Street, City 5",
                            Email = "sarah_diaz@email.com",
                            Password = "pass1125",
                            Phone = "0460620077",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "jenniferroberts143",
                            Address = "90 Roberts Street, City 7",
                            Email = "jennifer_roberts@email.com",
                            Password = "pass8280",
                            Phone = "0487387878",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        },
                        new
                        {
                            Username = "richardhall302",
                            Address = "28 Hall Street, City 6",
                            Email = "richard_hall@email.com",
                            Password = "pass5181",
                            Phone = "0461924169",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        },
                        new
                        {
                            Username = "maryhall268",
                            Address = "86 Hall Street, City 9",
                            Email = "mary_hall@email.com",
                            Password = "pass8613",
                            Phone = "0453451071",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\2.jpg"
                        },
                        new
                        {
                            Username = "barbaraparker204",
                            Address = "10 Parker Street, City 9",
                            Email = "barbara_parker@email.com",
                            Password = "pass5559",
                            Phone = "0460433857",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\4.jpg"
                        },
                        new
                        {
                            Username = "BankAdmin",
                            Address = "Head Office",
                            Email = "admin@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "MoeDegrasse",
                            Address = "17 Harper Street, City 2",
                            Email = "MoeDegrasse@email.com",
                            Password = "pass12",
                            Phone = "0444122322",
                            Picture = "C:\\Users\\jjse5\\Source\\Repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.HasOne("BankWebService.Models.UserProfile", "UserProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankWebService.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
