// <auto-generated />
using BankWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251018150538_SeedRefresh")]
    partial class SeedRefresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.HasIndex("Username");

                    b.ToTable("Bank_Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            Balance = 7781m,
                            Email = "elizabeth_rivera@email.com",
                            Name = "Elizabeth's Account 1",
                            Username = "elizabethrivera552"
                        },
                        new
                        {
                            AccountNumber = 2,
                            Balance = 2355m,
                            Email = "elizabeth_edwards@email.com",
                            Name = "Elizabeth's Account 1",
                            Username = "elizabethedwards766"
                        },
                        new
                        {
                            AccountNumber = 3,
                            Balance = 9163m,
                            Email = "elizabeth_edwards@email.com",
                            Name = "Elizabeth's Account 2",
                            Username = "elizabethedwards766"
                        },
                        new
                        {
                            AccountNumber = 4,
                            Balance = 6405m,
                            Email = "elizabeth_edwards@email.com",
                            Name = "Elizabeth's Account 3",
                            Username = "elizabethedwards766"
                        },
                        new
                        {
                            AccountNumber = 5,
                            Balance = 9788m,
                            Email = "elizabeth_edwards@email.com",
                            Name = "Elizabeth's Account 4",
                            Username = "elizabethedwards766"
                        },
                        new
                        {
                            AccountNumber = 6,
                            Balance = 3359m,
                            Email = "elizabeth_edwards@email.com",
                            Name = "Elizabeth's Account 5",
                            Username = "elizabethedwards766"
                        },
                        new
                        {
                            AccountNumber = 7,
                            Balance = 6700m,
                            Email = "jennifer_cruz@email.com",
                            Name = "Jennifer's Account 1",
                            Username = "jennifercruz522"
                        },
                        new
                        {
                            AccountNumber = 8,
                            Balance = 9177m,
                            Email = "michael_reyes@email.com",
                            Name = "Michael's Account 1",
                            Username = "michaelreyes839"
                        },
                        new
                        {
                            AccountNumber = 9,
                            Balance = 5072m,
                            Email = "michael_reyes@email.com",
                            Name = "Michael's Account 2",
                            Username = "michaelreyes839"
                        },
                        new
                        {
                            AccountNumber = 10,
                            Balance = 7051m,
                            Email = "michael_reyes@email.com",
                            Name = "Michael's Account 3",
                            Username = "michaelreyes839"
                        },
                        new
                        {
                            AccountNumber = 11,
                            Balance = 570m,
                            Email = "jessica_parker@email.com",
                            Name = "Jessica's Account 1",
                            Username = "jessicaparker180"
                        },
                        new
                        {
                            AccountNumber = 12,
                            Balance = 5645m,
                            Email = "jessica_parker@email.com",
                            Name = "Jessica's Account 2",
                            Username = "jessicaparker180"
                        },
                        new
                        {
                            AccountNumber = 13,
                            Balance = 4469m,
                            Email = "richard_diaz@email.com",
                            Name = "Richard's Account 1",
                            Username = "richarddiaz386"
                        },
                        new
                        {
                            AccountNumber = 14,
                            Balance = 6969m,
                            Email = "patricia_cruz@email.com",
                            Name = "Patricia's Account 1",
                            Username = "patriciacruz655"
                        },
                        new
                        {
                            AccountNumber = 15,
                            Balance = 2524m,
                            Email = "patricia_cruz@email.com",
                            Name = "Patricia's Account 2",
                            Username = "patriciacruz655"
                        },
                        new
                        {
                            AccountNumber = 16,
                            Balance = 8682m,
                            Email = "patricia_cruz@email.com",
                            Name = "Patricia's Account 3",
                            Username = "patriciacruz655"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN ('Deposit','Withdraw')");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = 1,
                            Amount = 575m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = 1,
                            Amount = 35m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountNumber = 1,
                            Amount = 769m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountNumber = 1,
                            Amount = 553m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountNumber = 1,
                            Amount = 698m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountNumber = 1,
                            Amount = 522m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountNumber = 1,
                            Amount = 945m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountNumber = 2,
                            Amount = 27m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountNumber = 2,
                            Amount = 373m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountNumber = 2,
                            Amount = 518m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountNumber = 2,
                            Amount = 951m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountNumber = 2,
                            Amount = 75m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountNumber = 2,
                            Amount = 260m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountNumber = 2,
                            Amount = 274m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountNumber = 2,
                            Amount = 485m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountNumber = 2,
                            Amount = 811m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountNumber = 2,
                            Amount = 400m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountNumber = 2,
                            Amount = 325m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountNumber = 3,
                            Amount = 723m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountNumber = 3,
                            Amount = 295m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountNumber = 3,
                            Amount = 812m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountNumber = 3,
                            Amount = 721m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountNumber = 3,
                            Amount = 58m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountNumber = 3,
                            Amount = 672m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountNumber = 3,
                            Amount = 389m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountNumber = 3,
                            Amount = 423m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 27,
                            AccountNumber = 3,
                            Amount = 904m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 28,
                            AccountNumber = 3,
                            Amount = 312m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 29,
                            AccountNumber = 4,
                            Amount = 190m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 30,
                            AccountNumber = 4,
                            Amount = 802m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 31,
                            AccountNumber = 4,
                            Amount = 117m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 32,
                            AccountNumber = 4,
                            Amount = 331m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 33,
                            AccountNumber = 4,
                            Amount = 102m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 34,
                            AccountNumber = 4,
                            Amount = 25m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 35,
                            AccountNumber = 4,
                            Amount = 501m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 36,
                            AccountNumber = 4,
                            Amount = 270m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 37,
                            AccountNumber = 4,
                            Amount = 846m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 38,
                            AccountNumber = 4,
                            Amount = 514m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 39,
                            AccountNumber = 4,
                            Amount = 65m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 40,
                            AccountNumber = 5,
                            Amount = 272m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 41,
                            AccountNumber = 5,
                            Amount = 607m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 42,
                            AccountNumber = 5,
                            Amount = 496m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 43,
                            AccountNumber = 5,
                            Amount = 60m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 44,
                            AccountNumber = 5,
                            Amount = 196m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 45,
                            AccountNumber = 5,
                            Amount = 746m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 46,
                            AccountNumber = 5,
                            Amount = 73m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 47,
                            AccountNumber = 5,
                            Amount = 753m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 48,
                            AccountNumber = 5,
                            Amount = 471m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 49,
                            AccountNumber = 5,
                            Amount = 933m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 50,
                            AccountNumber = 5,
                            Amount = 543m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 51,
                            AccountNumber = 5,
                            Amount = 958m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 52,
                            AccountNumber = 5,
                            Amount = 106m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 53,
                            AccountNumber = 6,
                            Amount = 752m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 54,
                            AccountNumber = 6,
                            Amount = 173m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 55,
                            AccountNumber = 6,
                            Amount = 931m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 56,
                            AccountNumber = 6,
                            Amount = 557m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 57,
                            AccountNumber = 6,
                            Amount = 824m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 58,
                            AccountNumber = 6,
                            Amount = 67m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 59,
                            AccountNumber = 6,
                            Amount = 595m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 60,
                            AccountNumber = 6,
                            Amount = 642m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 61,
                            AccountNumber = 7,
                            Amount = 419m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 62,
                            AccountNumber = 7,
                            Amount = 516m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 63,
                            AccountNumber = 7,
                            Amount = 256m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 64,
                            AccountNumber = 7,
                            Amount = 409m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 65,
                            AccountNumber = 7,
                            Amount = 912m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 66,
                            AccountNumber = 7,
                            Amount = 531m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 67,
                            AccountNumber = 8,
                            Amount = 569m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 68,
                            AccountNumber = 8,
                            Amount = 587m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 69,
                            AccountNumber = 8,
                            Amount = 232m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 70,
                            AccountNumber = 8,
                            Amount = 622m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 71,
                            AccountNumber = 8,
                            Amount = 673m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 72,
                            AccountNumber = 8,
                            Amount = 151m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 73,
                            AccountNumber = 8,
                            Amount = 35m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 74,
                            AccountNumber = 8,
                            Amount = 475m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 75,
                            AccountNumber = 8,
                            Amount = 171m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 76,
                            AccountNumber = 8,
                            Amount = 886m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 77,
                            AccountNumber = 8,
                            Amount = 564m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 78,
                            AccountNumber = 9,
                            Amount = 86m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 79,
                            AccountNumber = 9,
                            Amount = 855m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 80,
                            AccountNumber = 9,
                            Amount = 573m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 81,
                            AccountNumber = 9,
                            Amount = 374m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 82,
                            AccountNumber = 9,
                            Amount = 547m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 83,
                            AccountNumber = 9,
                            Amount = 157m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 84,
                            AccountNumber = 9,
                            Amount = 889m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 85,
                            AccountNumber = 9,
                            Amount = 927m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 86,
                            AccountNumber = 9,
                            Amount = 661m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 87,
                            AccountNumber = 10,
                            Amount = 287m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 88,
                            AccountNumber = 10,
                            Amount = 693m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 89,
                            AccountNumber = 10,
                            Amount = 584m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 90,
                            AccountNumber = 10,
                            Amount = 987m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 91,
                            AccountNumber = 10,
                            Amount = 740m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 92,
                            AccountNumber = 10,
                            Amount = 67m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 93,
                            AccountNumber = 10,
                            Amount = 392m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 94,
                            AccountNumber = 10,
                            Amount = 889m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 95,
                            AccountNumber = 11,
                            Amount = 978m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 96,
                            AccountNumber = 11,
                            Amount = 396m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 97,
                            AccountNumber = 11,
                            Amount = 527m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 98,
                            AccountNumber = 11,
                            Amount = 862m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 99,
                            AccountNumber = 11,
                            Amount = 390m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 100,
                            AccountNumber = 11,
                            Amount = 360m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 101,
                            AccountNumber = 11,
                            Amount = 816m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 102,
                            AccountNumber = 11,
                            Amount = 52m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 103,
                            AccountNumber = 12,
                            Amount = 253m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 104,
                            AccountNumber = 12,
                            Amount = 232m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 105,
                            AccountNumber = 12,
                            Amount = 978m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 106,
                            AccountNumber = 12,
                            Amount = 573m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 107,
                            AccountNumber = 12,
                            Amount = 384m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 108,
                            AccountNumber = 12,
                            Amount = 287m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 109,
                            AccountNumber = 12,
                            Amount = 968m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 110,
                            AccountNumber = 12,
                            Amount = 468m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 111,
                            AccountNumber = 12,
                            Amount = 909m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 112,
                            AccountNumber = 12,
                            Amount = 288m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 113,
                            AccountNumber = 12,
                            Amount = 119m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 114,
                            AccountNumber = 12,
                            Amount = 745m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 115,
                            AccountNumber = 12,
                            Amount = 281m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 116,
                            AccountNumber = 13,
                            Amount = 222m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 117,
                            AccountNumber = 13,
                            Amount = 491m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 118,
                            AccountNumber = 13,
                            Amount = 273m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 119,
                            AccountNumber = 13,
                            Amount = 794m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 120,
                            AccountNumber = 13,
                            Amount = 870m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 121,
                            AccountNumber = 14,
                            Amount = 677m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 122,
                            AccountNumber = 14,
                            Amount = 869m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 123,
                            AccountNumber = 14,
                            Amount = 367m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 124,
                            AccountNumber = 14,
                            Amount = 396m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 125,
                            AccountNumber = 14,
                            Amount = 549m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 126,
                            AccountNumber = 14,
                            Amount = 768m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 127,
                            AccountNumber = 14,
                            Amount = 787m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 128,
                            AccountNumber = 14,
                            Amount = 950m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 129,
                            AccountNumber = 14,
                            Amount = 158m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 130,
                            AccountNumber = 14,
                            Amount = 876m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 131,
                            AccountNumber = 14,
                            Amount = 968m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 132,
                            AccountNumber = 14,
                            Amount = 233m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 133,
                            AccountNumber = 15,
                            Amount = 188m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 134,
                            AccountNumber = 15,
                            Amount = 244m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 135,
                            AccountNumber = 15,
                            Amount = 345m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 136,
                            AccountNumber = 15,
                            Amount = 839m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 137,
                            AccountNumber = 15,
                            Amount = 689m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 138,
                            AccountNumber = 16,
                            Amount = 523m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 139,
                            AccountNumber = 16,
                            Amount = 976m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 140,
                            AccountNumber = 16,
                            Amount = 127m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 141,
                            AccountNumber = 16,
                            Amount = 462m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 142,
                            AccountNumber = 16,
                            Amount = 112m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 143,
                            AccountNumber = 16,
                            Amount = 988m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 144,
                            AccountNumber = 16,
                            Amount = 317m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 145,
                            AccountNumber = 16,
                            Amount = 985m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 146,
                            AccountNumber = 16,
                            Amount = 349m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 147,
                            AccountNumber = 16,
                            Amount = 634m,
                            Type = "Deposit"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Username = "elizabethrivera552",
                            Address = "78 Rivera Street, City 9",
                            Email = "elizabeth_rivera@email.com",
                            Password = "pass5330",
                            Phone = "0436463503",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "elizabethedwards766",
                            Address = "150 Edwards Street, City 1",
                            Email = "elizabeth_edwards@email.com",
                            Password = "pass6785",
                            Phone = "0446077880",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "jennifercruz522",
                            Address = "113 Cruz Street, City 8",
                            Email = "jennifer_cruz@email.com",
                            Password = "pass2375",
                            Phone = "0491244836",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\4.jpg"
                        },
                        new
                        {
                            Username = "michaelreyes839",
                            Address = "9 Reyes Street, City 2",
                            Email = "michael_reyes@email.com",
                            Password = "pass8454",
                            Phone = "0457564300",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\2.jpg"
                        },
                        new
                        {
                            Username = "jessicaparker180",
                            Address = "82 Parker Street, City 9",
                            Email = "jessica_parker@email.com",
                            Password = "pass8826",
                            Phone = "0457038127",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\2.jpg"
                        },
                        new
                        {
                            Username = "richarddiaz386",
                            Address = "124 Diaz Street, City 9",
                            Email = "richard_diaz@email.com",
                            Password = "pass3434",
                            Phone = "0426641971",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\4.jpg"
                        },
                        new
                        {
                            Username = "patriciacruz655",
                            Address = "110 Cruz Street, City 6",
                            Email = "patricia_cruz@email.com",
                            Password = "pass3965",
                            Phone = "0435489511",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "BankAdmin",
                            Address = "Head Office",
                            Email = "admin@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "MoeDegrasse",
                            Address = "17 Harper Street, City 2",
                            Email = "MoeDegrasse@email.com",
                            Password = "pass12",
                            Phone = "0444122322",
                            Picture = "C:\\Sean\\Sean\\Curtin\\2025 Sem 2\\DC\\Assignment 2\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.HasOne("BankWebService.Models.UserProfile", "UserProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankWebService.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
