// <auto-generated />
using BankWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251017030204_SeedRefresh")]
    partial class SeedRefresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.HasIndex("Username");

                    b.ToTable("Bank_Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            Balance = 9769m,
                            Email = "robert_hall@email.com",
                            Username = "roberthall206"
                        },
                        new
                        {
                            AccountNumber = 2,
                            Balance = 7181m,
                            Email = "robert_hall@email.com",
                            Username = "roberthall206"
                        },
                        new
                        {
                            AccountNumber = 3,
                            Balance = 260m,
                            Email = "robert_baker@email.com",
                            Username = "robertbaker240"
                        },
                        new
                        {
                            AccountNumber = 4,
                            Balance = 9183m,
                            Email = "robert_baker@email.com",
                            Username = "robertbaker240"
                        },
                        new
                        {
                            AccountNumber = 5,
                            Balance = 3631m,
                            Email = "robert_baker@email.com",
                            Username = "robertbaker240"
                        },
                        new
                        {
                            AccountNumber = 6,
                            Balance = 800m,
                            Email = "robert_parker@email.com",
                            Username = "robertparker737"
                        },
                        new
                        {
                            AccountNumber = 7,
                            Balance = 8742m,
                            Email = "robert_parker@email.com",
                            Username = "robertparker737"
                        },
                        new
                        {
                            AccountNumber = 8,
                            Balance = 7645m,
                            Email = "robert_parker@email.com",
                            Username = "robertparker737"
                        },
                        new
                        {
                            AccountNumber = 9,
                            Balance = 547m,
                            Email = "joseph_adams@email.com",
                            Username = "josephadams360"
                        },
                        new
                        {
                            AccountNumber = 10,
                            Balance = 5763m,
                            Email = "barbara_roberts@email.com",
                            Username = "barbararoberts109"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN ('Deposit','Withdraw')");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = 1,
                            Amount = 154m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = 1,
                            Amount = 122m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountNumber = 1,
                            Amount = 499m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountNumber = 1,
                            Amount = 370m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountNumber = 2,
                            Amount = 216m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountNumber = 2,
                            Amount = 108m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountNumber = 3,
                            Amount = 941m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountNumber = 3,
                            Amount = 754m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountNumber = 3,
                            Amount = 470m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountNumber = 3,
                            Amount = 86m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountNumber = 4,
                            Amount = 455m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountNumber = 4,
                            Amount = 888m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountNumber = 4,
                            Amount = 959m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountNumber = 4,
                            Amount = 421m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountNumber = 5,
                            Amount = 579m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountNumber = 5,
                            Amount = 717m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountNumber = 5,
                            Amount = 385m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountNumber = 6,
                            Amount = 820m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountNumber = 6,
                            Amount = 499m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountNumber = 6,
                            Amount = 462m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountNumber = 6,
                            Amount = 823m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountNumber = 6,
                            Amount = 320m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountNumber = 6,
                            Amount = 951m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountNumber = 6,
                            Amount = 266m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountNumber = 6,
                            Amount = 731m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountNumber = 6,
                            Amount = 903m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 27,
                            AccountNumber = 7,
                            Amount = 185m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 28,
                            AccountNumber = 7,
                            Amount = 652m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 29,
                            AccountNumber = 7,
                            Amount = 686m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 30,
                            AccountNumber = 7,
                            Amount = 288m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 31,
                            AccountNumber = 7,
                            Amount = 425m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 32,
                            AccountNumber = 8,
                            Amount = 518m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 33,
                            AccountNumber = 8,
                            Amount = 23m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 34,
                            AccountNumber = 8,
                            Amount = 992m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 35,
                            AccountNumber = 8,
                            Amount = 665m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 36,
                            AccountNumber = 8,
                            Amount = 621m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 37,
                            AccountNumber = 8,
                            Amount = 969m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 38,
                            AccountNumber = 8,
                            Amount = 502m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 39,
                            AccountNumber = 8,
                            Amount = 146m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 40,
                            AccountNumber = 8,
                            Amount = 776m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 41,
                            AccountNumber = 9,
                            Amount = 493m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 42,
                            AccountNumber = 9,
                            Amount = 59m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 43,
                            AccountNumber = 9,
                            Amount = 851m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 44,
                            AccountNumber = 9,
                            Amount = 690m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 45,
                            AccountNumber = 9,
                            Amount = 591m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 46,
                            AccountNumber = 9,
                            Amount = 333m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 47,
                            AccountNumber = 9,
                            Amount = 906m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 48,
                            AccountNumber = 9,
                            Amount = 797m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 49,
                            AccountNumber = 10,
                            Amount = 698m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 50,
                            AccountNumber = 10,
                            Amount = 279m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 51,
                            AccountNumber = 10,
                            Amount = 856m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 52,
                            AccountNumber = 10,
                            Amount = 356m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 53,
                            AccountNumber = 10,
                            Amount = 860m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 54,
                            AccountNumber = 10,
                            Amount = 64m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 55,
                            AccountNumber = 10,
                            Amount = 887m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 56,
                            AccountNumber = 10,
                            Amount = 652m,
                            Type = "Deposit"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Username = "roberthall206",
                            Address = "43 Hall Street, City 7",
                            Email = "robert_hall@email.com",
                            Password = "pass9037",
                            Phone = "0473506488",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "robertbaker240",
                            Address = "109 Baker Street, City 6",
                            Email = "robert_baker@email.com",
                            Password = "pass6132",
                            Phone = "0428432091",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "robertparker737",
                            Address = "159 Parker Street, City 6",
                            Email = "robert_parker@email.com",
                            Password = "pass7172",
                            Phone = "0442074826",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        },
                        new
                        {
                            Username = "josephadams360",
                            Address = "140 Adams Street, City 1",
                            Email = "joseph_adams@email.com",
                            Password = "pass9813",
                            Phone = "0432004499",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        },
                        new
                        {
                            Username = "barbararoberts109",
                            Address = "29 Roberts Street, City 7",
                            Email = "barbara_roberts@email.com",
                            Password = "pass2691",
                            Phone = "0467060979",
                            Picture = "C:\\Users\\jjse5\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\2.jpg"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.HasOne("BankWebService.Models.UserProfile", "UserProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankWebService.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
