// <auto-generated />
using BankWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    partial class DBManagerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.HasIndex("Username");

                    b.ToTable("Bank_Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            Balance = 1279m,
                            Email = "linda_green@email.com",
                            Username = "lindagreen180"
                        },
                        new
                        {
                            AccountNumber = 2,
                            Balance = 9602m,
                            Email = "linda_green@email.com",
                            Username = "lindagreen180"
                        },
                        new
                        {
                            AccountNumber = 3,
                            Balance = 7485m,
                            Email = "linda_green@email.com",
                            Username = "lindagreen180"
                        },
                        new
                        {
                            AccountNumber = 4,
                            Balance = 3544m,
                            Email = "jennifer_gomez@email.com",
                            Username = "jennifergomez600"
                        },
                        new
                        {
                            AccountNumber = 5,
                            Balance = 9229m,
                            Email = "jennifer_gomez@email.com",
                            Username = "jennifergomez600"
                        },
                        new
                        {
                            AccountNumber = 6,
                            Balance = 6070m,
                            Email = "jennifer_gomez@email.com",
                            Username = "jennifergomez600"
                        },
                        new
                        {
                            AccountNumber = 7,
                            Balance = 6897m,
                            Email = "joseph_evans@email.com",
                            Username = "josephevans238"
                        },
                        new
                        {
                            AccountNumber = 8,
                            Balance = 132m,
                            Email = "joseph_evans@email.com",
                            Username = "josephevans238"
                        },
                        new
                        {
                            AccountNumber = 9,
                            Balance = 8517m,
                            Email = "joseph_evans@email.com",
                            Username = "josephevans238"
                        },
                        new
                        {
                            AccountNumber = 10,
                            Balance = 4357m,
                            Email = "michael_hall@email.com",
                            Username = "michaelhall325"
                        },
                        new
                        {
                            AccountNumber = 11,
                            Balance = 8198m,
                            Email = "michael_hall@email.com",
                            Username = "michaelhall325"
                        },
                        new
                        {
                            AccountNumber = 12,
                            Balance = 5285m,
                            Email = "michael_hall@email.com",
                            Username = "michaelhall325"
                        },
                        new
                        {
                            AccountNumber = 13,
                            Balance = 4144m,
                            Email = "richard_reyes@email.com",
                            Username = "richardreyes172"
                        },
                        new
                        {
                            AccountNumber = 14,
                            Balance = 5442m,
                            Email = "richard_reyes@email.com",
                            Username = "richardreyes172"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN ('Deposit','Withdraw')");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = 1,
                            Amount = 850m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = 1,
                            Amount = 611m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountNumber = 1,
                            Amount = 961m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountNumber = 1,
                            Amount = 402m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountNumber = 1,
                            Amount = 895m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 6,
                            AccountNumber = 1,
                            Amount = 98m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 7,
                            AccountNumber = 1,
                            Amount = 479m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 8,
                            AccountNumber = 2,
                            Amount = 587m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 9,
                            AccountNumber = 2,
                            Amount = 20m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 10,
                            AccountNumber = 2,
                            Amount = 425m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 11,
                            AccountNumber = 2,
                            Amount = 712m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountNumber = 2,
                            Amount = 658m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountNumber = 3,
                            Amount = 442m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountNumber = 3,
                            Amount = 984m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountNumber = 3,
                            Amount = 111m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountNumber = 4,
                            Amount = 442m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountNumber = 4,
                            Amount = 97m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountNumber = 4,
                            Amount = 902m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountNumber = 4,
                            Amount = 488m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountNumber = 4,
                            Amount = 207m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountNumber = 4,
                            Amount = 365m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountNumber = 4,
                            Amount = 157m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountNumber = 5,
                            Amount = 547m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountNumber = 5,
                            Amount = 800m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountNumber = 5,
                            Amount = 606m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountNumber = 6,
                            Amount = 266m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 27,
                            AccountNumber = 6,
                            Amount = 68m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 28,
                            AccountNumber = 6,
                            Amount = 643m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 29,
                            AccountNumber = 6,
                            Amount = 865m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 30,
                            AccountNumber = 6,
                            Amount = 376m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 31,
                            AccountNumber = 6,
                            Amount = 973m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 32,
                            AccountNumber = 6,
                            Amount = 590m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 33,
                            AccountNumber = 6,
                            Amount = 422m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 34,
                            AccountNumber = 6,
                            Amount = 453m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 35,
                            AccountNumber = 7,
                            Amount = 429m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 36,
                            AccountNumber = 7,
                            Amount = 379m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 37,
                            AccountNumber = 7,
                            Amount = 107m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 38,
                            AccountNumber = 7,
                            Amount = 708m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 39,
                            AccountNumber = 7,
                            Amount = 962m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 40,
                            AccountNumber = 7,
                            Amount = 874m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 41,
                            AccountNumber = 7,
                            Amount = 961m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 42,
                            AccountNumber = 7,
                            Amount = 807m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 43,
                            AccountNumber = 8,
                            Amount = 26m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 44,
                            AccountNumber = 8,
                            Amount = 352m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 45,
                            AccountNumber = 8,
                            Amount = 112m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 46,
                            AccountNumber = 9,
                            Amount = 436m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 47,
                            AccountNumber = 9,
                            Amount = 818m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 48,
                            AccountNumber = 9,
                            Amount = 188m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 49,
                            AccountNumber = 10,
                            Amount = 722m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 50,
                            AccountNumber = 10,
                            Amount = 258m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 51,
                            AccountNumber = 10,
                            Amount = 307m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 52,
                            AccountNumber = 10,
                            Amount = 132m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 53,
                            AccountNumber = 10,
                            Amount = 548m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 54,
                            AccountNumber = 11,
                            Amount = 378m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 55,
                            AccountNumber = 11,
                            Amount = 308m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 56,
                            AccountNumber = 11,
                            Amount = 541m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 57,
                            AccountNumber = 11,
                            Amount = 978m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 58,
                            AccountNumber = 11,
                            Amount = 993m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 59,
                            AccountNumber = 12,
                            Amount = 955m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 60,
                            AccountNumber = 12,
                            Amount = 62m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 61,
                            AccountNumber = 12,
                            Amount = 539m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 62,
                            AccountNumber = 13,
                            Amount = 652m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 63,
                            AccountNumber = 13,
                            Amount = 168m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 64,
                            AccountNumber = 13,
                            Amount = 939m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 65,
                            AccountNumber = 13,
                            Amount = 360m,
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 66,
                            AccountNumber = 13,
                            Amount = 966m,
                            Type = "Withdraw"
                        },
                        new
                        {
                            TransactionId = 67,
                            AccountNumber = 14,
                            Amount = 65m,
                            Type = "Withdraw"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Username = "lindagreen180",
                            Address = "22 Green Street, City 4",
                            Email = "linda_green@email.com",
                            Password = "pass2596",
                            Phone = "0432569628",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "jennifergomez600",
                            Address = "169 Gomez Street, City 7",
                            Email = "jennifer_gomez@email.com",
                            Password = "pass7064",
                            Phone = "0498755253",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\5.jpg"
                        },
                        new
                        {
                            Username = "josephevans238",
                            Address = "5 Evans Street, City 4",
                            Email = "joseph_evans@email.com",
                            Password = "pass2605",
                            Phone = "0469833335",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        },
                        new
                        {
                            Username = "michaelhall325",
                            Address = "57 Hall Street, City 8",
                            Email = "michael_hall@email.com",
                            Password = "pass8756",
                            Phone = "0472765138",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        },
                        new
                        {
                            Username = "richardreyes172",
                            Address = "165 Reyes Street, City 8",
                            Email = "richard_reyes@email.com",
                            Password = "pass5413",
                            Phone = "0434803145",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\3.jpg"
                        },
                        new
                        {
                            Username = "BankAdmin",
                            Address = "Head Office",
                            Email = "admin@bank.local",
                            Password = "ChangeMe!123",
                            Phone = "+0000000000",
                            Picture = "/images/admin.png"
                        },
                        new
                        {
                            Username = "MoeDegrasse",
                            Address = "17 Harper Street, City 2",
                            Email = "MoeDegrasse@email.com",
                            Password = "pass12",
                            Phone = "0444122322",
                            Picture = "C:\\Users\\joshu\\source\\repos\\DC_Assignment_2\\resources\\ProfilePictures\\1.jpg"
                        });
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.HasOne("BankWebService.Models.UserProfile", "UserProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BankWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankWebService.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankWebService.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankWebService.Models.UserProfile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
